#!/bin/bash


EXT=$1

if [ -z "$1" ]; then
    echo "Error: Missing file extension."
    exit 1
fi

SCAN_PATH="/srv/ftp/scans"
DEVICE_NAME="brother4:bus2;dev1"


# Find the next available filename
N=1
while [[ -e "$SCAN_PATH/brother-scan-$(printf '%03d' "$N").$EXT" ]]; do
    ((N++))
done

OUTPUT="$SCAN_PATH/brother-scan-$(printf '%03d' "$N").$EXT"

scanimage -d "$DEVICE_NAME" --format="$EXT" > "$OUTPUT" &
PID=$!

echo "Scanning → $OUTPUT"

# WORK AROUND FOR SCANNER TO WORK
sleep 1
kill -STOP "$PID"
sleep 1
kill -CONT "$PID"

wait "$PID"

# END WORK AROUND

if [[ $? -eq 0 ]]; then
    echo "Done: $OUTPUT"
    exit 0
else
    echo "Scan failed"
    rm -f "$OUTPUT"
    exit 1
fi

